// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpcMessage.proto

package cmdRpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CmdRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdRequest) Reset()         { *m = CmdRequest{} }
func (m *CmdRequest) String() string { return proto.CompactTextString(m) }
func (*CmdRequest) ProtoMessage()    {}
func (*CmdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpcMessage_b4e80337b52a3b6d, []int{0}
}
func (m *CmdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdRequest.Unmarshal(m, b)
}
func (m *CmdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdRequest.Marshal(b, m, deterministic)
}
func (dst *CmdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdRequest.Merge(dst, src)
}
func (m *CmdRequest) XXX_Size() int {
	return xxx_messageInfo_CmdRequest.Size(m)
}
func (m *CmdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CmdRequest proto.InternalMessageInfo

func (m *CmdRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CmdReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdReply) Reset()         { *m = CmdReply{} }
func (m *CmdReply) String() string { return proto.CompactTextString(m) }
func (*CmdReply) ProtoMessage()    {}
func (*CmdReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpcMessage_b4e80337b52a3b6d, []int{1}
}
func (m *CmdReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdReply.Unmarshal(m, b)
}
func (m *CmdReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdReply.Marshal(b, m, deterministic)
}
func (dst *CmdReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdReply.Merge(dst, src)
}
func (m *CmdReply) XXX_Size() int {
	return xxx_messageInfo_CmdReply.Size(m)
}
func (m *CmdReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdReply.DiscardUnknown(m)
}

var xxx_messageInfo_CmdReply proto.InternalMessageInfo

func (m *CmdReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CmdRequest)(nil), "cmdRpc.CmdRequest")
	proto.RegisterType((*CmdReply)(nil), "cmdRpc.CmdReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CmdTaskClient is the client API for CmdTask service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CmdTaskClient interface {
	RpcTask(ctx context.Context, in *CmdRequest, opts ...grpc.CallOption) (*CmdReply, error)
}

type cmdTaskClient struct {
	cc *grpc.ClientConn
}

func NewCmdTaskClient(cc *grpc.ClientConn) CmdTaskClient {
	return &cmdTaskClient{cc}
}

func (c *cmdTaskClient) RpcTask(ctx context.Context, in *CmdRequest, opts ...grpc.CallOption) (*CmdReply, error) {
	out := new(CmdReply)
	err := c.cc.Invoke(ctx, "/cmdRpc.CmdTask/RpcTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CmdTaskServer is the server API for CmdTask service.
type CmdTaskServer interface {
	RpcTask(context.Context, *CmdRequest) (*CmdReply, error)
}

func RegisterCmdTaskServer(s *grpc.Server, srv CmdTaskServer) {
	s.RegisterService(&_CmdTask_serviceDesc, srv)
}

func _CmdTask_RpcTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CmdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdTaskServer).RpcTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cmdRpc.CmdTask/RpcTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdTaskServer).RpcTask(ctx, req.(*CmdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CmdTask_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cmdRpc.CmdTask",
	HandlerType: (*CmdTaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RpcTask",
			Handler:    _CmdTask_RpcTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcMessage.proto",
}

func init() { proto.RegisterFile("rpcMessage.proto", fileDescriptor_rpcMessage_b4e80337b52a3b6d) }

var fileDescriptor_rpcMessage_b4e80337b52a3b6d = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2a, 0x48, 0xf6,
	0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0xce,
	0x4d, 0x09, 0x2a, 0x48, 0x56, 0x52, 0xe0, 0xe2, 0x72, 0xce, 0x4d, 0x09, 0x4a, 0x2d, 0x2c, 0x4d,
	0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0c, 0x02, 0xb3, 0x95, 0x54, 0xb8, 0x38, 0xc0, 0x2a, 0x0a, 0x72, 0x2a, 0x85, 0x24, 0xb8, 0xd8,
	0x73, 0x21, 0xc6, 0x40, 0x95, 0xc0, 0xb8, 0x46, 0x36, 0x5c, 0xec, 0xce, 0xb9, 0x29, 0x21, 0x89,
	0xc5, 0xd9, 0x42, 0x86, 0x5c, 0xec, 0x41, 0x05, 0xc9, 0x60, 0xa6, 0x90, 0x1e, 0xc4, 0x1a, 0x3d,
	0x84, 0x1d, 0x52, 0x02, 0x28, 0x62, 0x05, 0x39, 0x95, 0x4a, 0x0c, 0x4e, 0x86, 0x5c, 0x8a, 0xc9,
	0xf9, 0xb9, 0x7a, 0x79, 0x49, 0xc5, 0x7a, 0x79, 0xf9, 0x29, 0xa9, 0x7a, 0xa5, 0x25, 0x99, 0x39,
	0xc5, 0x20, 0x75, 0xde, 0x99, 0x25, 0xc5, 0x50, 0xf5, 0x4e, 0x5c, 0x41, 0x70, 0x4f, 0x04, 0x30,
	0x26, 0xb1, 0x81, 0xfd, 0x61, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x41, 0x4d, 0xae, 0xdb,
	0x00, 0x00, 0x00,
}
